# Generated by Django 5.2.17 on 2026-09-27 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('poster', models.URLField(blank=True, max_length=500)),
                ('backdrop', models.URLField(blank=True, max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('genre', models.CharField(db_index=True, max_length=100)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField(help_text='Duration in minutes')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('language', models.CharField(default='English', max_length=80)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='movies', to='movies.category')),
            ],
            options={
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
